version: '3.8'

services:
  ai-app:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_IMAGE_API_URL=${IMAGE_API_URL:-https://api.gpt.ge}
      - VITE_IMAGE_API_KEY=${IMAGE_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
